/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  session: Session;
  user: User;
  verification: Verification;
  beneficiary: BeneficiaryTable;
  program_enrollment: ProgramEnrollmentTable;
  benefit_release: BenefitReleaseTable;
  claim: ClaimTable;
}

export interface BeneficiaryTable {
  id: string;
  firstName: string;
  middleName: string | null;
  lastName: string;
  dateOfBirth: string;
  gender: string;
  civilStatus: string;
  contactNumber: string;
  email: string | null;
  barangay: string;
  municipality: string;
  province: string;
  applicationStatus: string;
  dateRegistered: string;
  dateApproved: string | null;
  dateRejected: string | null;
  dateReleased: string | null;
  rejectionReason: string | null;
  approvedBy: string | null;
}

export interface ProgramEnrollmentTable {
  id: Generated<number>;
  beneficiaryId: string;
  program: string;
  enrolledDate: string;
  status: string;
}

export interface BenefitReleaseTable {
  id: string;
  beneficiaryId: string;
  program: string;
  assistanceType: string;
  amount: number;
  dateReleased: string;
  releasingOfficer: string;
  remarks: string | null;
}

export interface ClaimTable {
  id: string;
  beneficiaryId: string;
  program: string;
  description: string;
  amount: number;
  dateClaimed: string;
  status: string;
}
