services:
  postgres:
    image: postgres:16-alpine
    container_name: cod-postgres
    restart: unless-stopped
    ports:
      - "$DB_PORT:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
